"""
pdf_parser.py — Structured PDF Ingestion Engine for Cambridge International Past Papers.

Overview:
  This module implements a multi-stage parser designed to extract structured question data,
  diagram crops, options, and mark scheme answers from Cambridge International (CAIE) PDFs.
  It uses PyMuPDF4LLM for layout-aware document-to-markdown conversion, paired with custom
  regex state machines for option splitting and Mark Scheme spatial mapping.

Pipeline Stages:
  1. Metadata Extraction: Derives subject code, exam session, paper type, and year from filenames.
  2. Question Paper Parsing (`parse_question_paper`):
     - Invokes `pymupdf4llm.to_markdown` to generate structured Markdown and extract embedded graphics.
     - Splits document content by question index headers (`- **1**` or `**1**`).
     - Removes OCR picture-text artifacts generated by LLM Vision/Layout tools.
     - Extracts options via table regex or universal label matching (`**A**`, `**B**`, `**C**`, `**D**`).
     - Extracts image file references and cleans up page headers, copyright disclaimers, and blank pages.
     - Normalizes `<br>` tags and scientific notation tags (`<sup>`, `<sub>`) for frontend Markdown rendering.
  3. Mark Scheme Parsing (`parse_mark_scheme`):
     - Extracts answer keys using spatial coordinate analysis (Y-row bucketing) and regex tokenization.
     - Supports inline answer formats (`1 B`) and structured table layouts (`Q1 | B`).
     - Collects multi-line SAQ rubric guidance mapped to question indices.
  4. Merging (`_merge_answers`):
     - Joins Mark Scheme answers/rubrics into corresponding question data objects.
     - Automatically flags correct options for MCQ records (`is_correct = True`).
"""

from __future__ import annotations

import os
import re
import uuid
from pathlib import Path
from typing import Any

import fitz  # PyMuPDF engine for spatial text extraction

# Layout and Spatial Constants
MARGIN_TOP: float = 60.0
MARGIN_BOTTOM: float = 788.0

# Horizontal threshold (in PDF points) for identifying left-aligned question index tokens
Q_NUM_MAX_X: float = 85.0

# Regex Matchers
# Matches standard question numbers at line starts (e.g., "1 ", "12 ")
_Q_NUM_RE = re.compile(r"^\s*(\d{1,2})(?:\s|$)")

# Matches mark allocations in square brackets (e.g., "[1]", "[3]")
_MARK_RE = re.compile(r"\[\s*(\d+)\s*\]")

# Matches option prefixes in simple text streams (e.g., "A ", "A  Text")
_MCQ_OPT_RE = re.compile(r"^\s*([A-D])(?:\s+(.*)|$)")

# Matches alphabetical sub-part identifiers (e.g., "(a) State the...", "i) Calculate...")
_SUBPART_RE = re.compile(r"^\s*(\([a-z]+\)|[ivx]+\))\s+(.+)")

# Matches mark scheme answer key rows (e.g., "1  B", "12  C")
_MS_MCQ_ANS_RE = re.compile(r"^\s*(\d{1,2})\s+([A-D])\b")

# Keywords indicating partial credit or alternative acceptable answers in rubrics
_MS_ALLOW_RE = re.compile(r"(?i)allow|accept|credit")

# Default subdirectory for extracted PDF image crops
_IMAGES_SUBDIR = "uploads/extracted_images"


def _paper_meta(pdf_path: str) -> dict[str, Any]:
    """Extract metadata (subject code, session, paper type, year) from a PDF filename.

    Expected filename pattern:
      `{subject}_{session}_{type}_{variant}.pdf` (e.g., `9700_s23_qp_12.pdf` -> Subject 9700, Summer 2023, Paper 12)
    
    If the filename does not conform to standard naming conventions, safe default values are provided.
    """
    file_name = os.path.basename(pdf_path)
    name_no_ext = os.path.splitext(file_name)[0]
    parts = name_no_ext.split("_")

    if len(parts) >= 4:
        subject_code = parts[0]
        session_year = parts[1]
        variant = parts[3]
        paper_type = f"p{variant}"
        try:
            # Parse year from session string (e.g., 's23' -> 2023, 'w21' -> 2021)
            actual_year = 2000 + int(session_year[1:])
        except ValueError:
            actual_year = 2025
    else:
        subject_code = "9700"
        session_year = "s23"
        paper_type = "p12"
        actual_year = 2023

    return {
        "subject": subject_code,
        "session": session_year,
        "paper_type": paper_type,
        "year": actual_year,
    }


def parse_question_paper(qp_path: str, images_root: str | None = None) -> list[dict[str, Any]]:
    """Parse a Question Paper PDF file using PyMuPDF4LLM layout parsing.

    Args:
        qp_path: Absolute or relative path to the Question Paper PDF.
        images_root: Base filesystem path where extracted diagrams/images should be written.
                     If None, image extraction to disk is disabled.

    Returns:
        A list of parsed question records containing structured stems, options, image filenames,
        page regions, and paper metadata.
    """
    import pymupdf4llm
    
    meta = _paper_meta(qp_path)
    prefix = f"{meta['subject']}_{meta['session']}_{meta['paper_type']}"

    img_out_dir = None
    if images_root:
        img_out_dir = str(Path(images_root) / _IMAGES_SUBDIR)
        os.makedirs(img_out_dir, exist_ok=True)

    # Convert PDF to structured Markdown text while extracting embedded graphic assets
    md_text = pymupdf4llm.to_markdown(
        qp_path,
        write_images=bool(images_root),
        image_path=img_out_dir,
        image_format="png",
        dpi=150
    )

    # Identify question headers formatted by PyMuPDF4LLM as `- **1** ` or `**1** `
    # The negative lookahead (?!\\n) prevents matching bold page numbers sitting on standalone lines.
    start_pattern = r'(?:^|\n)[ \t]*(?:-[ \t]*\*\*(\d{1,2})\*\*\s+|\*\*(\d{1,2})\*\*[ \t]+(?!\n))'
    matches = list(re.finditer(start_pattern, md_text))
    
    questions: list[dict[str, Any]] = []
    
    for i, m in enumerate(matches):
        q_num = int(m.group(1) or m.group(2))
        start_idx = m.end()
        end_idx = matches[i+1].start() if i + 1 < len(matches) else len(md_text)
        content = md_text[start_idx:end_idx].strip()
        
        # 1. Remove OCR picture-text blocks generated by layout parsing (diagram graphics extracted separately)
        content = re.sub(r'<!--\s*Start of picture text\s*-->.*?<!--\s*End of picture text\s*-->', '', content, flags=re.DOTALL)
        content = re.sub(r'<!--.*?-->', '', content, flags=re.DOTALL)

        # 2. Strip page footers, UCLES copyright disclaimers, page turn hints, and blank page markers
        content = re.sub(r'(?:^|\n)\s*(?:\*+)?\s*(?:© UCLES|\[Turn over|BLANK PAGE).*', '', content, flags=re.DOTALL | re.IGNORECASE)
        
        options = []
        
        # Option Extraction Strategy 1: Check for Markdown options formatted inside grid tables
        table_opt_pattern = re.compile(r'\|\s*\*\*([A-D])\*\*\s*\|(.*?)(?=\n|$)', re.DOTALL)
        table_matches = table_opt_pattern.findall(content)
        if table_matches:
            for opt_char, opt_text in table_matches:
                clean_text = opt_text.replace('|', ' ').strip()
                # Preserve superscripts/subscripts for formulas, strip all other HTML
                clean_text = re.sub(r'<(?!sup|/sup|sub|/sub)[^>]+>', ' ', clean_text).strip()
                options.append({'label': opt_char, 'text': clean_text, 'is_correct': False})
            
            # Remove table markup lines after options are extracted
            content = '\n'.join([line for line in content.split('\n') if '|' not in line])
        else:
            # Option Extraction Strategy 2: Universal option matcher for inline ("**A** val1 **B** val2") or list formats
            opt_pattern = re.compile(r'(?:^|\s)(?:-\s*)?\*\*([A-D])\*\*\s+')
            opt_matches = list(opt_pattern.finditer(content))
            
            # Require at least 2 matched option markers to confirm MCQ option section
            if len(opt_matches) >= 2:
                for idx, m_opt in enumerate(opt_matches):
                    opt_char = m_opt.group(1)
                    start = m_opt.end()
                    end = opt_matches[idx+1].start() if idx + 1 < len(opt_matches) else len(content)
                    opt_text = content[start:end]
                    clean_text = re.sub(r'<(?!sup|/sup|sub|/sub)[^>]+>', ' ', opt_text).strip()
                    options.append({'label': opt_char, 'text': clean_text, 'is_correct': False})
                
                # Truncate question stem at the beginning of the option block
                content = content[:opt_matches[0].start()].strip()
                    
        # Extract embedded diagram image filenames referenced in markdown ![alt](path)
        images = []
        img_pattern = re.compile(r'!\[.*?\]\((.*?)\)')
        for img_match in img_pattern.findall(content):
            basename = os.path.basename(img_match)
            images.append(basename)
        content = img_pattern.sub('', content)
        
        # Format HTML break tags into Markdown line breaks (`  \n`) for proper React Markdown rendering
        content = re.sub(r'<br\s*/?>', '  \n', content)
        # Strip all HTML tags EXCEPT <sup> and <sub>
        content = re.sub(r'<(?!sup|/sup|sub|/sub)[^>]+>', ' ', content)
        # Collapse multiple consecutive empty newlines into standard double-newlines
        content = re.sub(r'\n{3,}', '\n\n', content)
        content = content.strip()
        
        # Fallback for Paper 1 (MCQ variants) when options are embedded inside complex unparsed graphics
        is_mcq_paper = meta["paper_type"].startswith("p1")
        if is_mcq_paper and not options:
            options = [
                {'label': 'A', 'text': '', 'is_correct': False},
                {'label': 'B', 'text': '', 'is_correct': False},
                {'label': 'C', 'text': '', 'is_correct': False},
                {'label': 'D', 'text': '', 'is_correct': False},
            ]
            
        questions.append({
            "id":         f"{prefix}_q{q_num}",
            "q_num":      q_num,
            "q_type":     "MCQ" if is_mcq_paper else ("SAQ" if not options else "MCQ"),
            "subject":    meta["subject"],
            "session":    meta["session"],
            "paper_type": meta["paper_type"],
            "year":       meta["year"],
            "topic":      "Unknown",
            "marks":      1 if options else 0,
            "stem":       content,
            "options":    options,
            "sub_parts":  [],
            "images":     images,
            "regions":    [],
            "pdf":        os.path.abspath(qp_path),
        })

    return questions


# Mark Scheme Parser


def parse_mark_scheme(ms_path: str) -> dict[int, str]:
    """Parse a Mark Scheme PDF file and return question answers/rubrics.

    Args:
        ms_path: Path to the Mark Scheme PDF file.

    Returns:
        A dictionary mapping question numbers (e.g., 1, 2) to correct answer strings.
        - For MCQ papers, returns single letter strings (e.g., {1: 'B', 2: 'A'}).
        - For SAQ papers, returns concatenated rubric text for each question.
    """
    answers: dict[int, str] = {}
    if not ms_path or not os.path.exists(ms_path):
        return answers

    _SINGLE_INT = re.compile(r"^\d{1,2}$")
    _SINGLE_ABCD = re.compile(r"^[A-D]$")

    doc = fitz.open(ms_path)
    current_q_num: int | None = None
    current_rubric: list[str] = []

    for page_num in range(len(doc)):
        page = doc[page_num]
        page_dict = page.get_text("dict")

        # Collect raw text spans along with bounding box coordinates
        all_spans: list[tuple[float, float, str]] = []
        for block in page_dict["blocks"]:
            if block.get("type") != 0:
                continue
            for line in block["lines"]:
                x0, y0, x1, y1 = line["bbox"]
                text = " ".join(span["text"] for span in line["spans"]).strip()
                if text:
                    all_spans.append((x0, y0, text))

        # Sort text spans vertically by Y position (using 5px rounding buckets), then horizontally by X
        all_spans.sort(key=lambda t: (round(t[1] / 5) * 5, t[0]))

        # Group text spans into horizontal Y-rows (tolerance window of 8 pixels)
        rows: list[list[tuple[float, float, str]]] = []
        for span in all_spans:
            x0, y0, text = span
            if not rows or abs(rows[-1][0][1] - y0) > 8:
                rows.append([(x0, y0, text)])
            else:
                rows[-1].append((x0, y0, text))

        for row in rows:
            tokens = [t[2] for t in row]

            # Layout Pattern A: Single token containing "1  B" or "12  D"
            for tok in tokens:
                mcq_m = _MS_MCQ_ANS_RE.match(tok)
                if mcq_m:
                    answers[int(mcq_m.group(1))] = mcq_m.group(2).strip()

            # Layout Pattern B: Separate table cells for question number and option key on same horizontal row
            ints = [int(t) for t in tokens if _SINGLE_INT.match(t)]
            abcds = [t for t in tokens if _SINGLE_ABCD.match(t)]
            if ints and abcds and not any(_MS_MCQ_ANS_RE.match(t) for t in tokens):
                for q_num, ans in zip(ints, abcds):
                    if 1 <= q_num <= 100:
                        answers[q_num] = ans

            # Layout Pattern C: SAQ marking rubric text starting with a left-margin question index
            for x0, y0, text in row:
                num_m = _Q_NUM_RE.match(text)
                if num_m and x0 < Q_NUM_MAX_X and not _SINGLE_INT.match(text.strip()):
                    if current_q_num is not None and current_rubric:
                        existing = answers.get(current_q_num, "")
                        rubric_text = " ".join(current_rubric).strip()
                        answers[current_q_num] = (existing + " " + rubric_text).strip() if existing else rubric_text
                    current_q_num = int(num_m.group(1))
                    current_rubric = [_Q_NUM_RE.sub("", text, count=1).strip()]
                elif current_q_num is not None and x0 > Q_NUM_MAX_X:
                    if text not in abcds:
                        current_rubric.append(text.strip())

    # Flush final accumulated SAQ rubric buffer
    if current_q_num is not None and current_rubric:
        existing = answers.get(current_q_num, "")
        rubric_text = " ".join(current_rubric).strip()
        answers[current_q_num] = (existing + " " + rubric_text).strip() if existing else rubric_text

    doc.close()
    return answers


# Merge QP + MS


def _merge_answers(questions: list[dict[str, Any]], ms_answers: dict[int, str]) -> list[dict[str, Any]]:
    """Correlate parsed Mark Scheme answers back into the Question Paper questions list."""
    for q in questions:
        q_num = q["q_num"]
        answer = ms_answers.get(q_num, "")
        q["marking_scheme"] = answer

        if q["q_type"] == "MCQ" and len(answer) == 1 and answer.upper() in "ABCD":
            # Set boolean is_correct flags on matching option labels
            for opt in q["options"]:
                opt["is_correct"] = opt["label"].upper() == answer.upper()
        elif q["sub_parts"]:
            # Attach SAQ rubric guidance to the primary sub-part
            if q["sub_parts"]:
                q["sub_parts"][0]["rubric"] = answer

    return questions


# Public Entry Points


def parse_paper(qp_path: str, ms_path: str | None = None, images_root: str | None = None) -> list[dict[str, Any]]:
    """Execute full parsing pipeline: parse QP, parse optional MS, and merge answers.

    Args:
        qp_path: Path to Question Paper PDF.
        ms_path: Path to Mark Scheme PDF (optional).
        images_root: Base directory for storing extracted graphic assets.

    Returns:
        Complete list of structured question data dictionaries.
    """
    questions = parse_question_paper(qp_path, images_root=images_root)
    if ms_path:
        ms_answers = parse_mark_scheme(ms_path)
        questions = _merge_answers(questions, ms_answers)
    return questions


def parse_all_papers(papers_dir: str, subject_code: str) -> list[dict[str, Any]]:
    """Recursively discover and parse all Question Paper PDFs in a given directory."""
    all_questions: list[dict[str, Any]] = []
    for root, _, files in os.walk(papers_dir):
        for file in files:
            if file.endswith(".pdf"):
                all_questions.extend(parse_paper(os.path.join(root, file)))
    return all_questions
