/**
 * Exports the TypeScript demo dataset to api/seed_data.json for the Python
 * seeder to load on first run.
 *
 * The demo content — 30-odd real question stems, the academic taxonomy, the
 * 120-student cohort and its ~3,000 simulated responses — was authored in
 * src/data/*.ts. Retyping it into Python would be busywork with a high chance
 * of transcription errors, so it is bundled with esbuild, executed once, and
 * dumped as JSON.
 *
 * Note what is deliberately NOT exported: the hand-written irtA/irtB values and
 * the derived stats. The backend refits those from the exported responses with
 * the real girth 3PL model, and re-derives the AI signal by calling
 * ai_analysis.py. Only genuine inputs cross the boundary.
 *
 *   node scripts/export-seed.mjs
 */

import { mkdtempSync, rmSync, writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import * as esbuild from 'esbuild';

const here = path.dirname(fileURLToPath(import.meta.url));
const webapp = path.resolve(here, '..');
const repoRoot = path.resolve(webapp, '..');
const outFile = path.join(repoRoot, 'api', 'seed_data.json');

const work = mkdtempSync(path.join(tmpdir(), 'itemiq-seed-'));
const bundle = path.join(work, 'seed.mjs');

try {
  await esbuild.build({
    entryPoints: [path.join(webapp, 'scripts/seed-source/seed.ts')],
    outfile: bundle,
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: 'node20',
    logLevel: 'warning',
    // The fixture sources are self-contained under scripts/seed-source/.
  });

  const { buildSeed, USERS, STUDENTS, PROGRAMS } = await import(pathToFileURL(bundle).href);
  const seed = buildSeed();

  // Faculty/AI difficulty labels and review remarks live on the question
  // records; strip everything the backend recomputes for itself.
  const questions = seed.questions.map((q) => ({
    id: q.id,
    type: q.type,
    subtopicId: q.subtopicId ?? null,
    descriptionId: q.descriptionId ?? null,
    stem: q.stem,
    options: q.options.map((o) => ({ text: o.text, isCorrect: o.isCorrect })),
    correctIndex: q.options.findIndex((o) => o.isCorrect),
    facultyDifficulty: q.facultyDifficulty,
    cognitiveLevel: q.cognitiveLevel ?? '',
    explanation: q.explanation ?? '',
    reference: q.reference ?? '',
    status: q.status,
    authorId: q.authorId,
    createdAt: q.createdAt,
    updatedAt: q.updatedAt,
    reviewRemark: q.reviewRemark ?? null,
    isBankSeed: q.id.startsWith('q-'),
  }));

  const payload = {
    generatedAt: new Date().toISOString(),
    note: 'Generated by webapp/scripts/export-seed.mjs. Do not edit by hand.',
    users: USERS,
    programs: PROGRAMS,
    students: STUDENTS,
    taxonomy: seed.taxonomy,
    questions,
    responses: seed.responses,
    requests: seed.requests,
    tos: seed.tos,
    examPapers: seed.examPapers,
  };

  mkdirSync(path.dirname(outFile), { recursive: true });
  writeFileSync(outFile, JSON.stringify(payload, null, 2), 'utf8');

  console.log(
    `Wrote ${path.relative(repoRoot, outFile)}: ` +
      `${payload.users.length} users, ${payload.students.length} students, ` +
      `${questions.length} questions, ${payload.responses.length} responses.`,
  );
} finally {
  rmSync(work, { recursive: true, force: true });
}
